// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv2WoUOoGjS7JGUoj21eE4LrUEekSca2U',
    appId: '1:526550089575:web:0e3b7ae04c95898473b9c2',
    messagingSenderId: '526550089575',
    projectId: 'samir-trainer-app',
    authDomain: 'samir-trainer-app.firebaseapp.com',
    storageBucket: 'samir-trainer-app.firebasestorage.app',
    measurementId: 'G-2TE9LB35D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCliavpf4cbi9rLsRBnLN4OA-r4vZG4yd8',
    appId: '1:526550089575:android:a4664327b4d59a7a73b9c2',
    messagingSenderId: '526550089575',
    projectId: 'samir-trainer-app',
    storageBucket: 'samir-trainer-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpKPOr36ndi6TbIlM0nKFd4yEy_tcb2lM',
    appId: '1:526550089575:ios:6239aa28a029311b73b9c2',
    messagingSenderId: '526550089575',
    projectId: 'samir-trainer-app',
    storageBucket: 'samir-trainer-app.firebasestorage.app',
    iosBundleId: 'com.example.samirTrainerApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpKPOr36ndi6TbIlM0nKFd4yEy_tcb2lM',
    appId: '1:526550089575:ios:6239aa28a029311b73b9c2',
    messagingSenderId: '526550089575',
    projectId: 'samir-trainer-app',
    storageBucket: 'samir-trainer-app.firebasestorage.app',
    iosBundleId: 'com.example.samirTrainerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv2WoUOoGjS7JGUoj21eE4LrUEekSca2U',
    appId: '1:526550089575:web:aebb08a456ab29d973b9c2',
    messagingSenderId: '526550089575',
    projectId: 'samir-trainer-app',
    authDomain: 'samir-trainer-app.firebaseapp.com',
    storageBucket: 'samir-trainer-app.firebasestorage.app',
    measurementId: 'G-TGXMJ25NS7',
  );
}
